name: 'Run dartanalyzer with reviewdog'
description: '🐶 Run dartanalyzer with reviewdog on pull requests to enforce best practices'
author: 'Hans'

inputs:

  github_token:
    description: 'GITHUB_TOKEN'
    required: true

  level:
    description: 'Report level for reviewdog [info,warning,error]'
    required: false
    default: 'error'

  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    required: false
    default: 'github-pr-check'

  filter_mode:
    description: |
      Filter mode of reviewdog command [added,diff_context,file,nofilter]
      Default is added.
    required: false
    default: 'added'

  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''

  workdir:
    description: "The directory from which to run dartanalyzer. Default '.'"
    default: '.'

runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        REVIEWDOG_VERSION: v0.11.0
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_WORKDIR: ${{ inputs.workdir }}

branding:
  icon: 'edit'
  color: 'blue'
