name: 'Run dartanalyzer with reviewdog'
description: '🐶 Run dartanalyzer with reviewdog on pull requests to enforce best practices'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    required: false
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    required: false
    default: 'github-pr-check'
  fail_on_error:
    description: |
      Fails the current check if any error was found [true/false]
      Default is false.
    required: false
    default: 'false'
  filter_mode:
    description: |
      Filter mode of reviewdog command [added,diff_context,file,nofilter]
      Default is added.
    required: false
    default: 'added'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  workdir:
    description: "The directory from which to run dartanalyzer. Default '.'"
    default: '.'
runs:
  using: 'composite'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
    - ${{ inputs.fail_on_error }}
    - ${{ inputs.filter_mode }}
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        REVIEWDOG_VERSION: v0.11.0
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
branding:
  icon: 'alert-octagon'
  color: 'blue'
